/*
 * Onfido Public API v3.6
 * The Onfido Public API (v3.6)
 *
 * The version of the OpenAPI document: v3.6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.onfido.model;

import java.util.Objects;
import java.util.Locale;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import java.util.Locale;
import com.google.gson.TypeAdapter;
import com.google.gson.JsonElement;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets applicant_consent_name
 */
@JsonAdapter(ApplicantConsentName.Adapter.class)
public enum ApplicantConsentName {
  
  PRIVACY_NOTICES_READ("privacy_notices_read"),
  
  SSN_VERIFICATION("ssn_verification"),
  
  PHONE_NUMBER_VERIFICATION("phone_number_verification"),
  
  UNKNOWN_DEFAULT_OPEN_API("unknown_default_open_api");

  private String value;

  ApplicantConsentName(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static ApplicantConsentName fromValue(String value) {
    for (ApplicantConsentName b : ApplicantConsentName.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    return UNKNOWN_DEFAULT_OPEN_API;
  }

  public static class Adapter extends TypeAdapter<ApplicantConsentName> {
    @Override
    public void write(final JsonWriter jsonWriter, final ApplicantConsentName enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public ApplicantConsentName read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return ApplicantConsentName.fromValue(value);
    }
  }

  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
    String value = jsonElement.getAsString();
    ApplicantConsentName.fromValue(value);
  }
}

