/*
 * Onfido API v3.6
 * The Onfido API
 *
 * The version of the OpenAPI document: 3.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.onfido.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.onfido.JSON;


/**
 * CheckResponse
 */
@JsonPropertyOrder({
  CheckResponse.JSON_PROPERTY_ID,
  CheckResponse.JSON_PROPERTY_CREATED_AT,
  CheckResponse.JSON_PROPERTY_HREF,
  CheckResponse.JSON_PROPERTY_STATUS,
  CheckResponse.JSON_PROPERTY_RESULT,
  CheckResponse.JSON_PROPERTY_FORM_URI,
  CheckResponse.JSON_PROPERTY_RESULTS_URI,
  CheckResponse.JSON_PROPERTY_REPORT_IDS,
  CheckResponse.JSON_PROPERTY_SANDBOX
})
@JsonTypeName("check_response")
@com.fasterxml.jackson.annotation.JsonIgnoreProperties(ignoreUnknown = true)
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.4.0")
public class CheckResponse {
  public static final String JSON_PROPERTY_ID = "id";
  private UUID id;

  public static final String JSON_PROPERTY_CREATED_AT = "created_at";
  private OffsetDateTime createdAt;

  public static final String JSON_PROPERTY_HREF = "href";
  private String href;

  /**
   * The current state of the check in the checking process.
   */
  public enum StatusEnum {
    IN_PROGRESS("in_progress"),
    
    AWAITING_APPLICANT("awaiting_applicant"),
    
    COMPLETE("complete"),
    
    WITHDRAWN("withdrawn"),
    
    PAUSED("paused"),
    
    REOPENED("reopened"),
    
    UNKNOWN_DEFAULT_OPEN_API("unknown_default_open_api");

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static StatusEnum fromValue(String value) {
      for (StatusEnum b : StatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      return UNKNOWN_DEFAULT_OPEN_API;
    }
  }

  public static final String JSON_PROPERTY_STATUS = "status";
  private StatusEnum status;

  /**
   * The overall result of the check, based on the results of the constituent reports.
   */
  public enum ResultEnum {
    CLEAR("clear"),
    
    CONSIDER("consider"),
    
    UNKNOWN_DEFAULT_OPEN_API("unknown_default_open_api");

    private String value;

    ResultEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static ResultEnum fromValue(String value) {
      for (ResultEnum b : ResultEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      return UNKNOWN_DEFAULT_OPEN_API;
    }
  }

  public static final String JSON_PROPERTY_RESULT = "result";
  private ResultEnum result;

  public static final String JSON_PROPERTY_FORM_URI = "form_uri";
  private String formUri;

  public static final String JSON_PROPERTY_RESULTS_URI = "results_uri";
  private String resultsUri;

  public static final String JSON_PROPERTY_REPORT_IDS = "report_ids";
  private List<UUID> reportIds;

  public static final String JSON_PROPERTY_SANDBOX = "sandbox";
  private Boolean sandbox;

  public CheckResponse() { 
  }

  public CheckResponse id(UUID id) {
    this.id = id;
    return this;
  }

   /**
   * The unique identifier for the check.
   * @return id
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public UUID getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setId(UUID id) {
    this.id = id;
  }


  public CheckResponse createdAt(OffsetDateTime createdAt) {
    this.createdAt = createdAt;
    return this;
  }

   /**
   * The date and time when this check was created.
   * @return createdAt
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CREATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }


  @JsonProperty(JSON_PROPERTY_CREATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCreatedAt(OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }


  public CheckResponse href(String href) {
    this.href = href;
    return this;
  }

   /**
   * The uri of this resource.
   * @return href
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_HREF)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getHref() {
    return href;
  }


  @JsonProperty(JSON_PROPERTY_HREF)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHref(String href) {
    this.href = href;
  }


  public CheckResponse status(StatusEnum status) {
    this.status = status;
    return this;
  }

   /**
   * The current state of the check in the checking process.
   * @return status
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public StatusEnum getStatus() {
    return status;
  }


  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStatus(StatusEnum status) {
    this.status = status;
  }


  public CheckResponse result(ResultEnum result) {
    this.result = result;
    return this;
  }

   /**
   * The overall result of the check, based on the results of the constituent reports.
   * @return result
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_RESULT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ResultEnum getResult() {
    return result;
  }


  @JsonProperty(JSON_PROPERTY_RESULT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setResult(ResultEnum result) {
    this.result = result;
  }


  public CheckResponse formUri(String formUri) {
    this.formUri = formUri;
    return this;
  }

   /**
   * A link to the applicant form, if &#x60;applicant_provides_data&#x60; is &#x60;true&#x60;.
   * @return formUri
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FORM_URI)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getFormUri() {
    return formUri;
  }


  @JsonProperty(JSON_PROPERTY_FORM_URI)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFormUri(String formUri) {
    this.formUri = formUri;
  }


  public CheckResponse resultsUri(String resultsUri) {
    this.resultsUri = resultsUri;
    return this;
  }

   /**
   * A link to the corresponding results page on the Onfido dashboard.
   * @return resultsUri
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_RESULTS_URI)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getResultsUri() {
    return resultsUri;
  }


  @JsonProperty(JSON_PROPERTY_RESULTS_URI)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setResultsUri(String resultsUri) {
    this.resultsUri = resultsUri;
  }


  public CheckResponse reportIds(List<UUID> reportIds) {
    this.reportIds = reportIds;
    return this;
  }

  public CheckResponse addReportIdsItem(UUID reportIdsItem) {
    if (this.reportIds == null) {
      this.reportIds = new ArrayList<>();
    }
    this.reportIds.add(reportIdsItem);
    return this;
  }

   /**
   * An array of report ids.
   * @return reportIds
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_REPORT_IDS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<UUID> getReportIds() {
    return reportIds;
  }


  @JsonProperty(JSON_PROPERTY_REPORT_IDS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setReportIds(List<UUID> reportIds) {
    this.reportIds = reportIds;
  }


  public CheckResponse sandbox(Boolean sandbox) {
    this.sandbox = sandbox;
    return this;
  }

   /**
   * Indicates whether the object was created in the sandbox or not.
   * @return sandbox
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SANDBOX)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getSandbox() {
    return sandbox;
  }


  @JsonProperty(JSON_PROPERTY_SANDBOX)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSandbox(Boolean sandbox) {
    this.sandbox = sandbox;
  }


  /**
   * Return true if this check_response object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CheckResponse checkResponse = (CheckResponse) o;
    return Objects.equals(this.id, checkResponse.id) &&
        Objects.equals(this.createdAt, checkResponse.createdAt) &&
        Objects.equals(this.href, checkResponse.href) &&
        Objects.equals(this.status, checkResponse.status) &&
        Objects.equals(this.result, checkResponse.result) &&
        Objects.equals(this.formUri, checkResponse.formUri) &&
        Objects.equals(this.resultsUri, checkResponse.resultsUri) &&
        Objects.equals(this.reportIds, checkResponse.reportIds) &&
        Objects.equals(this.sandbox, checkResponse.sandbox);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, createdAt, href, status, result, formUri, resultsUri, reportIds, sandbox);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CheckResponse {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    href: ").append(toIndentedString(href)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    result: ").append(toIndentedString(result)).append("\n");
    sb.append("    formUri: ").append(toIndentedString(formUri)).append("\n");
    sb.append("    resultsUri: ").append(toIndentedString(resultsUri)).append("\n");
    sb.append("    reportIds: ").append(toIndentedString(reportIds)).append("\n");
    sb.append("    sandbox: ").append(toIndentedString(sandbox)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

