/*
 * Onfido API v3.6
 * The Onfido API
 *
 * The version of the OpenAPI document: 3.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.onfido.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.onfido.model.DeviceIntelligenceBreakdownBreakdown;
import com.onfido.model.DeviceIntelligenceBreakdownProperties;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.onfido.JSON;


/**
 * DeviceIntelligenceBreakdown
 */
@JsonPropertyOrder({
  DeviceIntelligenceBreakdown.JSON_PROPERTY_BREAKDOWN,
  DeviceIntelligenceBreakdown.JSON_PROPERTY_PROPERTIES
})
@JsonTypeName("device_intelligence_breakdown")
@com.fasterxml.jackson.annotation.JsonIgnoreProperties(ignoreUnknown = true)
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class DeviceIntelligenceBreakdown {
  public static final String JSON_PROPERTY_BREAKDOWN = "breakdown";
  private DeviceIntelligenceBreakdownBreakdown breakdown;

  public static final String JSON_PROPERTY_PROPERTIES = "properties";
  private DeviceIntelligenceBreakdownProperties properties;

  public DeviceIntelligenceBreakdown() { 
  }

  public DeviceIntelligenceBreakdown breakdown(DeviceIntelligenceBreakdownBreakdown breakdown) {
    this.breakdown = breakdown;
    return this;
  }

   /**
   * Get breakdown
   * @return breakdown
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_BREAKDOWN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public DeviceIntelligenceBreakdownBreakdown getBreakdown() {
    return breakdown;
  }


  @JsonProperty(JSON_PROPERTY_BREAKDOWN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBreakdown(DeviceIntelligenceBreakdownBreakdown breakdown) {
    this.breakdown = breakdown;
  }


  public DeviceIntelligenceBreakdown properties(DeviceIntelligenceBreakdownProperties properties) {
    this.properties = properties;
    return this;
  }

   /**
   * Get properties
   * @return properties
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PROPERTIES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public DeviceIntelligenceBreakdownProperties getProperties() {
    return properties;
  }


  @JsonProperty(JSON_PROPERTY_PROPERTIES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProperties(DeviceIntelligenceBreakdownProperties properties) {
    this.properties = properties;
  }


  /**
   * Return true if this device_intelligence_breakdown object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DeviceIntelligenceBreakdown deviceIntelligenceBreakdown = (DeviceIntelligenceBreakdown) o;
    return Objects.equals(this.breakdown, deviceIntelligenceBreakdown.breakdown) &&
        Objects.equals(this.properties, deviceIntelligenceBreakdown.properties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(breakdown, properties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DeviceIntelligenceBreakdown {\n");
    sb.append("    breakdown: ").append(toIndentedString(breakdown)).append("\n");
    sb.append("    properties: ").append(toIndentedString(properties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

