/*
 * Onfido API v3.6
 * The Onfido API
 *
 * The version of the OpenAPI document: 3.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.onfido.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.onfido.model.DeviceIntelligenceBreakdownBreakdownDeviceBreakdown;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.onfido.JSON;


/**
 * Asserts whether the device used to upload the media is trustworthy, i.e. it is a real, physical device.
 */
@JsonPropertyOrder({
  DeviceIntelligenceBreakdownBreakdownDevice.JSON_PROPERTY_BREAKDOWN
})
@JsonTypeName("device_intelligence_breakdown_breakdown_device")
@com.fasterxml.jackson.annotation.JsonIgnoreProperties(ignoreUnknown = true)
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class DeviceIntelligenceBreakdownBreakdownDevice {
  public static final String JSON_PROPERTY_BREAKDOWN = "breakdown";
  private DeviceIntelligenceBreakdownBreakdownDeviceBreakdown breakdown;

  public DeviceIntelligenceBreakdownBreakdownDevice() { 
  }

  public DeviceIntelligenceBreakdownBreakdownDevice breakdown(DeviceIntelligenceBreakdownBreakdownDeviceBreakdown breakdown) {
    this.breakdown = breakdown;
    return this;
  }

   /**
   * Get breakdown
   * @return breakdown
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_BREAKDOWN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public DeviceIntelligenceBreakdownBreakdownDeviceBreakdown getBreakdown() {
    return breakdown;
  }


  @JsonProperty(JSON_PROPERTY_BREAKDOWN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBreakdown(DeviceIntelligenceBreakdownBreakdownDeviceBreakdown breakdown) {
    this.breakdown = breakdown;
  }


  /**
   * Return true if this device_intelligence_breakdown_breakdown_device object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DeviceIntelligenceBreakdownBreakdownDevice deviceIntelligenceBreakdownBreakdownDevice = (DeviceIntelligenceBreakdownBreakdownDevice) o;
    return Objects.equals(this.breakdown, deviceIntelligenceBreakdownBreakdownDevice.breakdown);
  }

  @Override
  public int hashCode() {
    return Objects.hash(breakdown);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DeviceIntelligenceBreakdownBreakdownDevice {\n");
    sb.append("    breakdown: ").append(toIndentedString(breakdown)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

