/*
 * Onfido Public API v3.6
 * The Onfido Public API (v3.6)
 *
 * The version of the OpenAPI document: v3.6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.onfido.model;

import java.util.Objects;
import java.util.Locale;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.onfido.model.FacialSimilarityPhotoBreakdownImageIntegrityBreakdownFaceDetected;
import com.onfido.model.FacialSimilarityPhotoBreakdownImageIntegrityBreakdownSourceIntegrity;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.Locale;

import com.onfido.JSON;

/**
 * FacialSimilarityPhotoBreakdownImageIntegrityBreakdown
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.16.0")
public class FacialSimilarityPhotoBreakdownImageIntegrityBreakdown {
  public static final String SERIALIZED_NAME_FACE_DETECTED = "face_detected";
  @SerializedName(SERIALIZED_NAME_FACE_DETECTED)
  @javax.annotation.Nullable
  private FacialSimilarityPhotoBreakdownImageIntegrityBreakdownFaceDetected faceDetected;

  public static final String SERIALIZED_NAME_SOURCE_INTEGRITY = "source_integrity";
  @SerializedName(SERIALIZED_NAME_SOURCE_INTEGRITY)
  @javax.annotation.Nullable
  private FacialSimilarityPhotoBreakdownImageIntegrityBreakdownSourceIntegrity sourceIntegrity;

  public FacialSimilarityPhotoBreakdownImageIntegrityBreakdown() {
  }

  public FacialSimilarityPhotoBreakdownImageIntegrityBreakdown faceDetected(@javax.annotation.Nullable FacialSimilarityPhotoBreakdownImageIntegrityBreakdownFaceDetected faceDetected) {
    this.faceDetected = faceDetected;
    return this;
  }

  /**
   * Get faceDetected
   * @return faceDetected
   */
  @javax.annotation.Nullable
  public FacialSimilarityPhotoBreakdownImageIntegrityBreakdownFaceDetected getFaceDetected() {
    return faceDetected;
  }

  public void setFaceDetected(@javax.annotation.Nullable FacialSimilarityPhotoBreakdownImageIntegrityBreakdownFaceDetected faceDetected) {
    this.faceDetected = faceDetected;
  }


  public FacialSimilarityPhotoBreakdownImageIntegrityBreakdown sourceIntegrity(@javax.annotation.Nullable FacialSimilarityPhotoBreakdownImageIntegrityBreakdownSourceIntegrity sourceIntegrity) {
    this.sourceIntegrity = sourceIntegrity;
    return this;
  }

  /**
   * Get sourceIntegrity
   * @return sourceIntegrity
   */
  @javax.annotation.Nullable
  public FacialSimilarityPhotoBreakdownImageIntegrityBreakdownSourceIntegrity getSourceIntegrity() {
    return sourceIntegrity;
  }

  public void setSourceIntegrity(@javax.annotation.Nullable FacialSimilarityPhotoBreakdownImageIntegrityBreakdownSourceIntegrity sourceIntegrity) {
    this.sourceIntegrity = sourceIntegrity;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the FacialSimilarityPhotoBreakdownImageIntegrityBreakdown instance itself
   */
  public FacialSimilarityPhotoBreakdownImageIntegrityBreakdown putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FacialSimilarityPhotoBreakdownImageIntegrityBreakdown facialSimilarityPhotoBreakdownImageIntegrityBreakdown = (FacialSimilarityPhotoBreakdownImageIntegrityBreakdown) o;
    return Objects.equals(this.faceDetected, facialSimilarityPhotoBreakdownImageIntegrityBreakdown.faceDetected) &&
        Objects.equals(this.sourceIntegrity, facialSimilarityPhotoBreakdownImageIntegrityBreakdown.sourceIntegrity)&&
        Objects.equals(this.additionalProperties, facialSimilarityPhotoBreakdownImageIntegrityBreakdown.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(faceDetected, sourceIntegrity, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FacialSimilarityPhotoBreakdownImageIntegrityBreakdown {\n");
    sb.append("    faceDetected: ").append(toIndentedString(faceDetected)).append("\n");
    sb.append("    sourceIntegrity: ").append(toIndentedString(sourceIntegrity)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("face_detected", "source_integrity"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to FacialSimilarityPhotoBreakdownImageIntegrityBreakdown
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!FacialSimilarityPhotoBreakdownImageIntegrityBreakdown.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The required field(s) %s in FacialSimilarityPhotoBreakdownImageIntegrityBreakdown is not found in the empty JSON string", FacialSimilarityPhotoBreakdownImageIntegrityBreakdown.openapiRequiredFields.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the optional field `face_detected`
      if (jsonObj.get("face_detected") != null && !jsonObj.get("face_detected").isJsonNull()) {
        FacialSimilarityPhotoBreakdownImageIntegrityBreakdownFaceDetected.validateJsonElement(jsonObj.get("face_detected"));
      }
      // validate the optional field `source_integrity`
      if (jsonObj.get("source_integrity") != null && !jsonObj.get("source_integrity").isJsonNull()) {
        FacialSimilarityPhotoBreakdownImageIntegrityBreakdownSourceIntegrity.validateJsonElement(jsonObj.get("source_integrity"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!FacialSimilarityPhotoBreakdownImageIntegrityBreakdown.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'FacialSimilarityPhotoBreakdownImageIntegrityBreakdown' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<FacialSimilarityPhotoBreakdownImageIntegrityBreakdown> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(FacialSimilarityPhotoBreakdownImageIntegrityBreakdown.class));

       return (TypeAdapter<T>) new TypeAdapter<FacialSimilarityPhotoBreakdownImageIntegrityBreakdown>() {
           @Override
           public void write(JsonWriter out, FacialSimilarityPhotoBreakdownImageIntegrityBreakdown value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additional properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   JsonElement jsonElement = gson.toJsonTree(entry.getValue());
                   if (jsonElement.isJsonArray()) {
                     obj.add(entry.getKey(), jsonElement.getAsJsonArray());
                   } else if (jsonElement.isJsonObject()) { 
                     obj.add(entry.getKey(), jsonElement.getAsJsonObject());
                   }
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public FacialSimilarityPhotoBreakdownImageIntegrityBreakdown read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             JsonObject jsonObj = jsonElement.getAsJsonObject();
             // store additional fields in the deserialized instance
             FacialSimilarityPhotoBreakdownImageIntegrityBreakdown instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format(Locale.ROOT, "The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of FacialSimilarityPhotoBreakdownImageIntegrityBreakdown given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of FacialSimilarityPhotoBreakdownImageIntegrityBreakdown
   * @throws IOException if the JSON string is invalid with respect to FacialSimilarityPhotoBreakdownImageIntegrityBreakdown
   */
  public static FacialSimilarityPhotoBreakdownImageIntegrityBreakdown fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, FacialSimilarityPhotoBreakdownImageIntegrityBreakdown.class);
  }

  /**
   * Convert an instance of FacialSimilarityPhotoBreakdownImageIntegrityBreakdown to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

