/*
 * Onfido API v3.6
 * The Onfido API
 *
 * The version of the OpenAPI document: 3.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.onfido.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.onfido.JSON;


/**
 * IndiaPanReportAllOfPropertiesDevice
 */
@JsonPropertyOrder({
  IndiaPanReportAllOfPropertiesDevice.JSON_PROPERTY_PAN,
  IndiaPanReportAllOfPropertiesDevice.JSON_PROPERTY_FULL_NAME
})
@JsonTypeName("india_pan_report_allOf_properties_device")
@com.fasterxml.jackson.annotation.JsonIgnoreProperties(ignoreUnknown = true)
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class IndiaPanReportAllOfPropertiesDevice {
  public static final String JSON_PROPERTY_PAN = "pan";
  private String pan;

  public static final String JSON_PROPERTY_FULL_NAME = "full_name";
  private String fullName;

  public IndiaPanReportAllOfPropertiesDevice() { 
  }

  public IndiaPanReportAllOfPropertiesDevice pan(String pan) {
    this.pan = pan;
    return this;
  }

   /**
   * The applicant&#39;s PAN (10 digit alphanumeric number).
   * @return pan
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PAN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPan() {
    return pan;
  }


  @JsonProperty(JSON_PROPERTY_PAN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPan(String pan) {
    this.pan = pan;
  }


  public IndiaPanReportAllOfPropertiesDevice fullName(String fullName) {
    this.fullName = fullName;
    return this;
  }

   /**
   * The applicant&#39;s full name.
   * @return fullName
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FULL_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getFullName() {
    return fullName;
  }


  @JsonProperty(JSON_PROPERTY_FULL_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFullName(String fullName) {
    this.fullName = fullName;
  }


  /**
   * Return true if this india_pan_report_allOf_properties_device object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IndiaPanReportAllOfPropertiesDevice indiaPanReportAllOfPropertiesDevice = (IndiaPanReportAllOfPropertiesDevice) o;
    return Objects.equals(this.pan, indiaPanReportAllOfPropertiesDevice.pan) &&
        Objects.equals(this.fullName, indiaPanReportAllOfPropertiesDevice.fullName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(pan, fullName);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IndiaPanReportAllOfPropertiesDevice {\n");
    sb.append("    pan: ").append(toIndentedString(pan)).append("\n");
    sb.append("    fullName: ").append(toIndentedString(fullName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

