/*
 * Onfido Public API v3.6
 * The Onfido Public API (v3.6)
 *
 * The version of the OpenAPI document: v3.6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.onfido.model;

import java.util.Objects;
import java.util.Locale;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.UUID;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.Locale;

import com.onfido.JSON;

/**
 * ResultsFeedback
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.16.0")
public class ResultsFeedback {
  /**
   * The expected result for the check or report.
   */
  @JsonAdapter(ExpectedResultEnum.Adapter.class)
  public enum ExpectedResultEnum {
    CLEAR("clear"),
    
    CONSIDER("consider"),
    
    UNKNOWN_DEFAULT_OPEN_API("unknown_default_open_api");

    private String value;

    ExpectedResultEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static ExpectedResultEnum fromValue(String value) {
      for (ExpectedResultEnum b : ExpectedResultEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      return UNKNOWN_DEFAULT_OPEN_API;
    }

    public static class Adapter extends TypeAdapter<ExpectedResultEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final ExpectedResultEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public ExpectedResultEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return ExpectedResultEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      ExpectedResultEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_EXPECTED_RESULT = "expected_result";
  @SerializedName(SERIALIZED_NAME_EXPECTED_RESULT)
  @javax.annotation.Nullable
  private ExpectedResultEnum expectedResult;

  public static final String SERIALIZED_NAME_CHECK_ID = "check_id";
  @SerializedName(SERIALIZED_NAME_CHECK_ID)
  @javax.annotation.Nullable
  private UUID checkId;

  public static final String SERIALIZED_NAME_REPORT_ID = "report_id";
  @SerializedName(SERIALIZED_NAME_REPORT_ID)
  @javax.annotation.Nullable
  private UUID reportId;

  public static final String SERIALIZED_NAME_FEEDBACK_NOTES = "feedback_notes";
  @SerializedName(SERIALIZED_NAME_FEEDBACK_NOTES)
  @javax.annotation.Nullable
  private String feedbackNotes;

  public ResultsFeedback() {
  }

  public ResultsFeedback expectedResult(@javax.annotation.Nullable ExpectedResultEnum expectedResult) {
    this.expectedResult = expectedResult;
    return this;
  }

  /**
   * The expected result for the check or report.
   * @return expectedResult
   */
  @javax.annotation.Nullable
  public ExpectedResultEnum getExpectedResult() {
    return expectedResult;
  }

  public void setExpectedResult(@javax.annotation.Nullable ExpectedResultEnum expectedResult) {
    this.expectedResult = expectedResult;
  }


  public ResultsFeedback checkId(@javax.annotation.Nullable UUID checkId) {
    this.checkId = checkId;
    return this;
  }

  /**
   * The ID of the check (only if report_id is not provided).
   * @return checkId
   */
  @javax.annotation.Nullable
  public UUID getCheckId() {
    return checkId;
  }

  public void setCheckId(@javax.annotation.Nullable UUID checkId) {
    this.checkId = checkId;
  }


  public ResultsFeedback reportId(@javax.annotation.Nullable UUID reportId) {
    this.reportId = reportId;
    return this;
  }

  /**
   * The ID of the check (only if check_id is not provided).
   * @return reportId
   */
  @javax.annotation.Nullable
  public UUID getReportId() {
    return reportId;
  }

  public void setReportId(@javax.annotation.Nullable UUID reportId) {
    this.reportId = reportId;
  }


  public ResultsFeedback feedbackNotes(@javax.annotation.Nullable String feedbackNotes) {
    this.feedbackNotes = feedbackNotes;
    return this;
  }

  /**
   * Any additional information or feedback.
   * @return feedbackNotes
   */
  @javax.annotation.Nullable
  public String getFeedbackNotes() {
    return feedbackNotes;
  }

  public void setFeedbackNotes(@javax.annotation.Nullable String feedbackNotes) {
    this.feedbackNotes = feedbackNotes;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the ResultsFeedback instance itself
   */
  public ResultsFeedback putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResultsFeedback resultsFeedback = (ResultsFeedback) o;
    return Objects.equals(this.expectedResult, resultsFeedback.expectedResult) &&
        Objects.equals(this.checkId, resultsFeedback.checkId) &&
        Objects.equals(this.reportId, resultsFeedback.reportId) &&
        Objects.equals(this.feedbackNotes, resultsFeedback.feedbackNotes)&&
        Objects.equals(this.additionalProperties, resultsFeedback.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(expectedResult, checkId, reportId, feedbackNotes, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResultsFeedback {\n");
    sb.append("    expectedResult: ").append(toIndentedString(expectedResult)).append("\n");
    sb.append("    checkId: ").append(toIndentedString(checkId)).append("\n");
    sb.append("    reportId: ").append(toIndentedString(reportId)).append("\n");
    sb.append("    feedbackNotes: ").append(toIndentedString(feedbackNotes)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("expected_result", "check_id", "report_id", "feedback_notes"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to ResultsFeedback
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ResultsFeedback.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The required field(s) %s in ResultsFeedback is not found in the empty JSON string", ResultsFeedback.openapiRequiredFields.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("expected_result") != null && !jsonObj.get("expected_result").isJsonNull()) && !jsonObj.get("expected_result").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `expected_result` to be a primitive type in the JSON string but got `%s`", jsonObj.get("expected_result").toString()));
      }
      // validate the optional field `expected_result`
      if (jsonObj.get("expected_result") != null && !jsonObj.get("expected_result").isJsonNull()) {
        ExpectedResultEnum.validateJsonElement(jsonObj.get("expected_result"));
      }
      if ((jsonObj.get("check_id") != null && !jsonObj.get("check_id").isJsonNull()) && !jsonObj.get("check_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `check_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("check_id").toString()));
      }
      if ((jsonObj.get("report_id") != null && !jsonObj.get("report_id").isJsonNull()) && !jsonObj.get("report_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `report_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("report_id").toString()));
      }
      if ((jsonObj.get("feedback_notes") != null && !jsonObj.get("feedback_notes").isJsonNull()) && !jsonObj.get("feedback_notes").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `feedback_notes` to be a primitive type in the JSON string but got `%s`", jsonObj.get("feedback_notes").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ResultsFeedback.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ResultsFeedback' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ResultsFeedback> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ResultsFeedback.class));

       return (TypeAdapter<T>) new TypeAdapter<ResultsFeedback>() {
           @Override
           public void write(JsonWriter out, ResultsFeedback value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additional properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   JsonElement jsonElement = gson.toJsonTree(entry.getValue());
                   if (jsonElement.isJsonArray()) {
                     obj.add(entry.getKey(), jsonElement.getAsJsonArray());
                   } else if (jsonElement.isJsonObject()) { 
                     obj.add(entry.getKey(), jsonElement.getAsJsonObject());
                   }
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public ResultsFeedback read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             JsonObject jsonObj = jsonElement.getAsJsonObject();
             // store additional fields in the deserialized instance
             ResultsFeedback instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format(Locale.ROOT, "The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of ResultsFeedback given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of ResultsFeedback
   * @throws IOException if the JSON string is invalid with respect to ResultsFeedback
   */
  public static ResultsFeedback fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ResultsFeedback.class);
  }

  /**
   * Convert an instance of ResultsFeedback to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

