/*
 * Onfido Public API v3.6
 * The Onfido Public API (v3.6)
 *
 * The version of the OpenAPI document: v3.6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.onfido.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.onfido.model.WatchlistAmlBreakdownAdverseMedia;
import com.onfido.model.WatchlistAmlBreakdownLegalAndRegulatoryWarnings;
import com.onfido.model.WatchlistAmlBreakdownPoliticallyExposedPerson;
import com.onfido.model.WatchlistAmlBreakdownSanction;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.onfido.JSON;

/**
 * WatchlistEnhancedBreakdown
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.11.0")
public class WatchlistEnhancedBreakdown {
  public static final String SERIALIZED_NAME_POLITICALLY_EXPOSED_PERSON = "politically_exposed_person";
  @SerializedName(SERIALIZED_NAME_POLITICALLY_EXPOSED_PERSON)
  @javax.annotation.Nullable
  private WatchlistAmlBreakdownPoliticallyExposedPerson politicallyExposedPerson;

  public static final String SERIALIZED_NAME_SANCTION = "sanction";
  @SerializedName(SERIALIZED_NAME_SANCTION)
  @javax.annotation.Nullable
  private WatchlistAmlBreakdownSanction sanction;

  public static final String SERIALIZED_NAME_ADVERSE_MEDIA = "adverse_media";
  @SerializedName(SERIALIZED_NAME_ADVERSE_MEDIA)
  @javax.annotation.Nullable
  private WatchlistAmlBreakdownAdverseMedia adverseMedia;

  public static final String SERIALIZED_NAME_MONITORED_LISTS = "monitored_lists";
  @SerializedName(SERIALIZED_NAME_MONITORED_LISTS)
  @javax.annotation.Nullable
  private WatchlistAmlBreakdownLegalAndRegulatoryWarnings monitoredLists;

  public WatchlistEnhancedBreakdown() {
  }

  public WatchlistEnhancedBreakdown politicallyExposedPerson(@javax.annotation.Nullable WatchlistAmlBreakdownPoliticallyExposedPerson politicallyExposedPerson) {
    this.politicallyExposedPerson = politicallyExposedPerson;
    return this;
  }

  /**
   * Get politicallyExposedPerson
   * @return politicallyExposedPerson
   */
  @javax.annotation.Nullable
  public WatchlistAmlBreakdownPoliticallyExposedPerson getPoliticallyExposedPerson() {
    return politicallyExposedPerson;
  }

  public void setPoliticallyExposedPerson(@javax.annotation.Nullable WatchlistAmlBreakdownPoliticallyExposedPerson politicallyExposedPerson) {
    this.politicallyExposedPerson = politicallyExposedPerson;
  }


  public WatchlistEnhancedBreakdown sanction(@javax.annotation.Nullable WatchlistAmlBreakdownSanction sanction) {
    this.sanction = sanction;
    return this;
  }

  /**
   * Get sanction
   * @return sanction
   */
  @javax.annotation.Nullable
  public WatchlistAmlBreakdownSanction getSanction() {
    return sanction;
  }

  public void setSanction(@javax.annotation.Nullable WatchlistAmlBreakdownSanction sanction) {
    this.sanction = sanction;
  }


  public WatchlistEnhancedBreakdown adverseMedia(@javax.annotation.Nullable WatchlistAmlBreakdownAdverseMedia adverseMedia) {
    this.adverseMedia = adverseMedia;
    return this;
  }

  /**
   * Get adverseMedia
   * @return adverseMedia
   */
  @javax.annotation.Nullable
  public WatchlistAmlBreakdownAdverseMedia getAdverseMedia() {
    return adverseMedia;
  }

  public void setAdverseMedia(@javax.annotation.Nullable WatchlistAmlBreakdownAdverseMedia adverseMedia) {
    this.adverseMedia = adverseMedia;
  }


  public WatchlistEnhancedBreakdown monitoredLists(@javax.annotation.Nullable WatchlistAmlBreakdownLegalAndRegulatoryWarnings monitoredLists) {
    this.monitoredLists = monitoredLists;
    return this;
  }

  /**
   * Get monitoredLists
   * @return monitoredLists
   */
  @javax.annotation.Nullable
  public WatchlistAmlBreakdownLegalAndRegulatoryWarnings getMonitoredLists() {
    return monitoredLists;
  }

  public void setMonitoredLists(@javax.annotation.Nullable WatchlistAmlBreakdownLegalAndRegulatoryWarnings monitoredLists) {
    this.monitoredLists = monitoredLists;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the WatchlistEnhancedBreakdown instance itself
   */
  public WatchlistEnhancedBreakdown putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WatchlistEnhancedBreakdown watchlistEnhancedBreakdown = (WatchlistEnhancedBreakdown) o;
    return Objects.equals(this.politicallyExposedPerson, watchlistEnhancedBreakdown.politicallyExposedPerson) &&
        Objects.equals(this.sanction, watchlistEnhancedBreakdown.sanction) &&
        Objects.equals(this.adverseMedia, watchlistEnhancedBreakdown.adverseMedia) &&
        Objects.equals(this.monitoredLists, watchlistEnhancedBreakdown.monitoredLists)&&
        Objects.equals(this.additionalProperties, watchlistEnhancedBreakdown.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(politicallyExposedPerson, sanction, adverseMedia, monitoredLists, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WatchlistEnhancedBreakdown {\n");
    sb.append("    politicallyExposedPerson: ").append(toIndentedString(politicallyExposedPerson)).append("\n");
    sb.append("    sanction: ").append(toIndentedString(sanction)).append("\n");
    sb.append("    adverseMedia: ").append(toIndentedString(adverseMedia)).append("\n");
    sb.append("    monitoredLists: ").append(toIndentedString(monitoredLists)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("politically_exposed_person");
    openapiFields.add("sanction");
    openapiFields.add("adverse_media");
    openapiFields.add("monitored_lists");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to WatchlistEnhancedBreakdown
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!WatchlistEnhancedBreakdown.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in WatchlistEnhancedBreakdown is not found in the empty JSON string", WatchlistEnhancedBreakdown.openapiRequiredFields.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the optional field `politically_exposed_person`
      if (jsonObj.get("politically_exposed_person") != null && !jsonObj.get("politically_exposed_person").isJsonNull()) {
        WatchlistAmlBreakdownPoliticallyExposedPerson.validateJsonElement(jsonObj.get("politically_exposed_person"));
      }
      // validate the optional field `sanction`
      if (jsonObj.get("sanction") != null && !jsonObj.get("sanction").isJsonNull()) {
        WatchlistAmlBreakdownSanction.validateJsonElement(jsonObj.get("sanction"));
      }
      // validate the optional field `adverse_media`
      if (jsonObj.get("adverse_media") != null && !jsonObj.get("adverse_media").isJsonNull()) {
        WatchlistAmlBreakdownAdverseMedia.validateJsonElement(jsonObj.get("adverse_media"));
      }
      // validate the optional field `monitored_lists`
      if (jsonObj.get("monitored_lists") != null && !jsonObj.get("monitored_lists").isJsonNull()) {
        WatchlistAmlBreakdownLegalAndRegulatoryWarnings.validateJsonElement(jsonObj.get("monitored_lists"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!WatchlistEnhancedBreakdown.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'WatchlistEnhancedBreakdown' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<WatchlistEnhancedBreakdown> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(WatchlistEnhancedBreakdown.class));

       return (TypeAdapter<T>) new TypeAdapter<WatchlistEnhancedBreakdown>() {
           @Override
           public void write(JsonWriter out, WatchlistEnhancedBreakdown value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additional properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   JsonElement jsonElement = gson.toJsonTree(entry.getValue());
                   if (jsonElement.isJsonArray()) {
                     obj.add(entry.getKey(), jsonElement.getAsJsonArray());
                   } else if (jsonElement.isJsonObject()) { 
                     obj.add(entry.getKey(), jsonElement.getAsJsonObject());
                   }
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public WatchlistEnhancedBreakdown read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             JsonObject jsonObj = jsonElement.getAsJsonObject();
             // store additional fields in the deserialized instance
             WatchlistEnhancedBreakdown instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of WatchlistEnhancedBreakdown given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of WatchlistEnhancedBreakdown
   * @throws IOException if the JSON string is invalid with respect to WatchlistEnhancedBreakdown
   */
  public static WatchlistEnhancedBreakdown fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, WatchlistEnhancedBreakdown.class);
  }

  /**
   * Convert an instance of WatchlistEnhancedBreakdown to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

