/*
 * Onfido Public API v3.6
 * The Onfido Public API (v3.6)
 *
 * The version of the OpenAPI document: v3.6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.onfido.model;

import java.util.Objects;
import java.util.Locale;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.Locale;

import com.onfido.JSON;

/**
 * WatchlistMeshAddedMentions
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.16.0")
public class WatchlistMeshAddedMentions {
  public static final String SERIALIZED_NAME_ADDED_AML_TYPES = "added_aml_types";
  @SerializedName(SERIALIZED_NAME_ADDED_AML_TYPES)
  @javax.annotation.Nullable
  private List<String> addedAmlTypes;

  public static final String SERIALIZED_NAME_ADDED_SNIPPETS = "added_snippets";
  @SerializedName(SERIALIZED_NAME_ADDED_SNIPPETS)
  @javax.annotation.Nullable
  private List<String> addedSnippets;

  public static final String SERIALIZED_NAME_ADDED_LISTINGS = "added_listings";
  @SerializedName(SERIALIZED_NAME_ADDED_LISTINGS)
  @javax.annotation.Nullable
  private List<String> addedListings;

  public WatchlistMeshAddedMentions() {
  }

  public WatchlistMeshAddedMentions addedAmlTypes(@javax.annotation.Nullable List<String> addedAmlTypes) {
    this.addedAmlTypes = addedAmlTypes;
    return this;
  }

  public WatchlistMeshAddedMentions addAddedAmlTypesItem(String addedAmlTypesItem) {
    if (this.addedAmlTypes == null) {
      this.addedAmlTypes = new ArrayList<>();
    }
    this.addedAmlTypes.add(addedAmlTypesItem);
    return this;
  }

  /**
   * Get addedAmlTypes
   * @return addedAmlTypes
   */
  @javax.annotation.Nullable
  public List<String> getAddedAmlTypes() {
    return addedAmlTypes;
  }

  public void setAddedAmlTypes(@javax.annotation.Nullable List<String> addedAmlTypes) {
    this.addedAmlTypes = addedAmlTypes;
  }


  public WatchlistMeshAddedMentions addedSnippets(@javax.annotation.Nullable List<String> addedSnippets) {
    this.addedSnippets = addedSnippets;
    return this;
  }

  public WatchlistMeshAddedMentions addAddedSnippetsItem(String addedSnippetsItem) {
    if (this.addedSnippets == null) {
      this.addedSnippets = new ArrayList<>();
    }
    this.addedSnippets.add(addedSnippetsItem);
    return this;
  }

  /**
   * Get addedSnippets
   * @return addedSnippets
   */
  @javax.annotation.Nullable
  public List<String> getAddedSnippets() {
    return addedSnippets;
  }

  public void setAddedSnippets(@javax.annotation.Nullable List<String> addedSnippets) {
    this.addedSnippets = addedSnippets;
  }


  public WatchlistMeshAddedMentions addedListings(@javax.annotation.Nullable List<String> addedListings) {
    this.addedListings = addedListings;
    return this;
  }

  public WatchlistMeshAddedMentions addAddedListingsItem(String addedListingsItem) {
    if (this.addedListings == null) {
      this.addedListings = new ArrayList<>();
    }
    this.addedListings.add(addedListingsItem);
    return this;
  }

  /**
   * Get addedListings
   * @return addedListings
   */
  @javax.annotation.Nullable
  public List<String> getAddedListings() {
    return addedListings;
  }

  public void setAddedListings(@javax.annotation.Nullable List<String> addedListings) {
    this.addedListings = addedListings;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the WatchlistMeshAddedMentions instance itself
   */
  public WatchlistMeshAddedMentions putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WatchlistMeshAddedMentions watchlistMeshAddedMentions = (WatchlistMeshAddedMentions) o;
    return Objects.equals(this.addedAmlTypes, watchlistMeshAddedMentions.addedAmlTypes) &&
        Objects.equals(this.addedSnippets, watchlistMeshAddedMentions.addedSnippets) &&
        Objects.equals(this.addedListings, watchlistMeshAddedMentions.addedListings)&&
        Objects.equals(this.additionalProperties, watchlistMeshAddedMentions.additionalProperties);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(addedAmlTypes, addedSnippets, addedListings, additionalProperties);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WatchlistMeshAddedMentions {\n");
    sb.append("    addedAmlTypes: ").append(toIndentedString(addedAmlTypes)).append("\n");
    sb.append("    addedSnippets: ").append(toIndentedString(addedSnippets)).append("\n");
    sb.append("    addedListings: ").append(toIndentedString(addedListings)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("added_aml_types", "added_snippets", "added_listings"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to WatchlistMeshAddedMentions
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!WatchlistMeshAddedMentions.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The required field(s) %s in WatchlistMeshAddedMentions is not found in the empty JSON string", WatchlistMeshAddedMentions.openapiRequiredFields.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // ensure the optional json data is an array if present
      if (jsonObj.get("added_aml_types") != null && !jsonObj.get("added_aml_types").isJsonNull() && !jsonObj.get("added_aml_types").isJsonArray()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `added_aml_types` to be an array in the JSON string but got `%s`", jsonObj.get("added_aml_types").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("added_snippets") != null && !jsonObj.get("added_snippets").isJsonNull() && !jsonObj.get("added_snippets").isJsonArray()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `added_snippets` to be an array in the JSON string but got `%s`", jsonObj.get("added_snippets").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("added_listings") != null && !jsonObj.get("added_listings").isJsonNull() && !jsonObj.get("added_listings").isJsonArray()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `added_listings` to be an array in the JSON string but got `%s`", jsonObj.get("added_listings").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!WatchlistMeshAddedMentions.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'WatchlistMeshAddedMentions' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<WatchlistMeshAddedMentions> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(WatchlistMeshAddedMentions.class));

       return (TypeAdapter<T>) new TypeAdapter<WatchlistMeshAddedMentions>() {
           @Override
           public void write(JsonWriter out, WatchlistMeshAddedMentions value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additional properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   JsonElement jsonElement = gson.toJsonTree(entry.getValue());
                   if (jsonElement.isJsonArray()) {
                     obj.add(entry.getKey(), jsonElement.getAsJsonArray());
                   } else if (jsonElement.isJsonObject()) { 
                     obj.add(entry.getKey(), jsonElement.getAsJsonObject());
                   }
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public WatchlistMeshAddedMentions read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             JsonObject jsonObj = jsonElement.getAsJsonObject();
             // store additional fields in the deserialized instance
             WatchlistMeshAddedMentions instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format(Locale.ROOT, "The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of WatchlistMeshAddedMentions given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of WatchlistMeshAddedMentions
   * @throws IOException if the JSON string is invalid with respect to WatchlistMeshAddedMentions
   */
  public static WatchlistMeshAddedMentions fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, WatchlistMeshAddedMentions.class);
  }

  /**
   * Convert an instance of WatchlistMeshAddedMentions to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

