/*
 * Onfido API v3.6
 * The Onfido API (v3.6)
 *
 * The version of the OpenAPI document: v3.6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.onfido.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.onfido.JSON;

/**
 * WatchlistMonitorMatchesUpdater
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.9.0")
public class WatchlistMonitorMatchesUpdater {
  public static final String SERIALIZED_NAME_ENABLE = "enable";
  @SerializedName(SERIALIZED_NAME_ENABLE)
  private List<UUID> enable = new ArrayList<>();

  public static final String SERIALIZED_NAME_DISABLE = "disable";
  @SerializedName(SERIALIZED_NAME_DISABLE)
  private List<UUID> disable = new ArrayList<>();

  public WatchlistMonitorMatchesUpdater() {
  }

  public WatchlistMonitorMatchesUpdater enable(List<UUID> enable) {
    this.enable = enable;
    return this;
  }

  public WatchlistMonitorMatchesUpdater addEnableItem(UUID enableItem) {
    if (this.enable == null) {
      this.enable = new ArrayList<>();
    }
    this.enable.add(enableItem);
    return this;
  }

  /**
   * Get enable
   * @return enable
   */
  @javax.annotation.Nullable
  public List<UUID> getEnable() {
    return enable;
  }

  public void setEnable(List<UUID> enable) {
    this.enable = enable;
  }


  public WatchlistMonitorMatchesUpdater disable(List<UUID> disable) {
    this.disable = disable;
    return this;
  }

  public WatchlistMonitorMatchesUpdater addDisableItem(UUID disableItem) {
    if (this.disable == null) {
      this.disable = new ArrayList<>();
    }
    this.disable.add(disableItem);
    return this;
  }

  /**
   * Get disable
   * @return disable
   */
  @javax.annotation.Nullable
  public List<UUID> getDisable() {
    return disable;
  }

  public void setDisable(List<UUID> disable) {
    this.disable = disable;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the WatchlistMonitorMatchesUpdater instance itself
   */
  public WatchlistMonitorMatchesUpdater putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WatchlistMonitorMatchesUpdater watchlistMonitorMatchesUpdater = (WatchlistMonitorMatchesUpdater) o;
    return Objects.equals(this.enable, watchlistMonitorMatchesUpdater.enable) &&
        Objects.equals(this.disable, watchlistMonitorMatchesUpdater.disable)&&
        Objects.equals(this.additionalProperties, watchlistMonitorMatchesUpdater.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(enable, disable, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WatchlistMonitorMatchesUpdater {\n");
    sb.append("    enable: ").append(toIndentedString(enable)).append("\n");
    sb.append("    disable: ").append(toIndentedString(disable)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("enable");
    openapiFields.add("disable");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to WatchlistMonitorMatchesUpdater
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!WatchlistMonitorMatchesUpdater.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in WatchlistMonitorMatchesUpdater is not found in the empty JSON string", WatchlistMonitorMatchesUpdater.openapiRequiredFields.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // ensure the optional json data is an array if present
      if (jsonObj.get("enable") != null && !jsonObj.get("enable").isJsonNull() && !jsonObj.get("enable").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `enable` to be an array in the JSON string but got `%s`", jsonObj.get("enable").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("disable") != null && !jsonObj.get("disable").isJsonNull() && !jsonObj.get("disable").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `disable` to be an array in the JSON string but got `%s`", jsonObj.get("disable").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!WatchlistMonitorMatchesUpdater.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'WatchlistMonitorMatchesUpdater' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<WatchlistMonitorMatchesUpdater> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(WatchlistMonitorMatchesUpdater.class));

       return (TypeAdapter<T>) new TypeAdapter<WatchlistMonitorMatchesUpdater>() {
           @Override
           public void write(JsonWriter out, WatchlistMonitorMatchesUpdater value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additional properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   JsonElement jsonElement = gson.toJsonTree(entry.getValue());
                   if (jsonElement.isJsonArray()) {
                     obj.add(entry.getKey(), jsonElement.getAsJsonArray());
                   } else if (jsonElement.isJsonObject()) { 
                     obj.add(entry.getKey(), jsonElement.getAsJsonObject());
                   }
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public WatchlistMonitorMatchesUpdater read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             JsonObject jsonObj = jsonElement.getAsJsonObject();
             // store additional fields in the deserialized instance
             WatchlistMonitorMatchesUpdater instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of WatchlistMonitorMatchesUpdater given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of WatchlistMonitorMatchesUpdater
   * @throws IOException if the JSON string is invalid with respect to WatchlistMonitorMatchesUpdater
   */
  public static WatchlistMonitorMatchesUpdater fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, WatchlistMonitorMatchesUpdater.class);
  }

  /**
   * Convert an instance of WatchlistMonitorMatchesUpdater to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

