/*
 * Onfido API v3.6
 * The Onfido API
 *
 * The version of the OpenAPI document: 3.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.onfido.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.onfido.JSON;


import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Gets or Sets webhook_event_type
 */
public enum WebhookEventType {
  
  AUDIT_LOG_CREATED("audit_log.created"),
  
  WATCHLIST_MONITOR_MATCHES_UPDATED("watchlist_monitor.matches_updated"),
  
  WORKFLOW_RUN_COMPLETED("workflow_run.completed"),
  
  WORKFLOW_TASK_STARTED("workflow_task.started"),
  
  WORKFLOW_TASK_COMPLETED("workflow_task.completed"),
  
  CHECK_STARTED("check.started"),
  
  CHECK_REOPENED("check.reopened"),
  
  CHECK_WITHDRAWN("check.withdrawn"),
  
  CHECK_COMPLETED("check.completed"),
  
  CHECK_FORM_COMPLETED("check.form_completed"),
  
  REPORT_WITHDRAWN("report.withdrawn"),
  
  REPORT_RESUMED("report.resumed"),
  
  REPORT_CANCELLED("report.cancelled"),
  
  REPORT_AWAITING_APPROVAL("report.awaiting_approval"),
  
  REPORT_COMPLETED("report.completed"),
  
  WORKFLOW_TIMELINE_FILE_CREATED("workflow_timeline_file.created"),
  
  WORKFLOW_SIGNED_EVIDENCE_FILE_CREATED("workflow_signed_evidence_file.created"),
  
  UNKNOWN_DEFAULT_OPEN_API("unknown_default_open_api");

  private String value;

  WebhookEventType(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static WebhookEventType fromValue(String value) {
    for (WebhookEventType b : WebhookEventType.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    return UNKNOWN_DEFAULT_OPEN_API;
  }
}

