/*
 * Onfido API v3.6
 * The Onfido API (v3.6)
 *
 * The version of the OpenAPI document: v3.6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.onfido.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.onfido.model.WorkflowRunError;
import com.onfido.model.WorkflowRunLink;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.onfido.JSON;

/**
 * The resource affected by this event.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.9.0")
public class WebhookEventPayloadResource {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private String id;

  public static final String SERIALIZED_NAME_APPLICANT_ID = "applicant_id";
  @SerializedName(SERIALIZED_NAME_APPLICANT_ID)
  private UUID applicantId;

  public static final String SERIALIZED_NAME_CREATED_AT = "created_at";
  @SerializedName(SERIALIZED_NAME_CREATED_AT)
  private OffsetDateTime createdAt;

  public static final String SERIALIZED_NAME_UPDATED_AT = "updated_at";
  @SerializedName(SERIALIZED_NAME_UPDATED_AT)
  private OffsetDateTime updatedAt;

  public static final String SERIALIZED_NAME_DASHBOARD_URL = "dashboard_url";
  @SerializedName(SERIALIZED_NAME_DASHBOARD_URL)
  private String dashboardUrl;

  public static final String SERIALIZED_NAME_WORKFLOW_ID = "workflow_id";
  @SerializedName(SERIALIZED_NAME_WORKFLOW_ID)
  private UUID workflowId;

  public static final String SERIALIZED_NAME_WORKFLOW_RUN_ID = "workflow_run_id";
  @SerializedName(SERIALIZED_NAME_WORKFLOW_RUN_ID)
  private UUID workflowRunId;

  public static final String SERIALIZED_NAME_WORKFLOW_VERSION_ID = "workflow_version_id";
  @SerializedName(SERIALIZED_NAME_WORKFLOW_VERSION_ID)
  private Integer workflowVersionId;

  public static final String SERIALIZED_NAME_TASK_DEF_ID = "task_def_id";
  @SerializedName(SERIALIZED_NAME_TASK_DEF_ID)
  private String taskDefId;

  public static final String SERIALIZED_NAME_TASK_DEF_VERSION = "task_def_version";
  @SerializedName(SERIALIZED_NAME_TASK_DEF_VERSION)
  private String taskDefVersion;

  public static final String SERIALIZED_NAME_INPUT = "input";
  @SerializedName(SERIALIZED_NAME_INPUT)
  private Object input;

  public static final String SERIALIZED_NAME_OUTPUT = "output";
  @SerializedName(SERIALIZED_NAME_OUTPUT)
  private Object output;

  public static final String SERIALIZED_NAME_REASONS = "reasons";
  @SerializedName(SERIALIZED_NAME_REASONS)
  private List<String> reasons = new ArrayList<>();

  public static final String SERIALIZED_NAME_LINK = "link";
  @SerializedName(SERIALIZED_NAME_LINK)
  private WorkflowRunLink link;

  public static final String SERIALIZED_NAME_ERROR = "error";
  @SerializedName(SERIALIZED_NAME_ERROR)
  private WorkflowRunError error;

  public WebhookEventPayloadResource() {
  }

  public WebhookEventPayloadResource id(String id) {
    this.id = id;
    return this;
  }

  /**
   * The identifier of the resource.
   * @return id
   */
  @javax.annotation.Nullable
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }


  public WebhookEventPayloadResource applicantId(UUID applicantId) {
    this.applicantId = applicantId;
    return this;
  }

  /**
   * The unique identifier for the Applicant.
   * @return applicantId
   */
  @javax.annotation.Nullable
  public UUID getApplicantId() {
    return applicantId;
  }

  public void setApplicantId(UUID applicantId) {
    this.applicantId = applicantId;
  }


  public WebhookEventPayloadResource createdAt(OffsetDateTime createdAt) {
    this.createdAt = createdAt;
    return this;
  }

  /**
   * The date and time when the resource was created.
   * @return createdAt
   */
  @javax.annotation.Nullable
  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }


  public WebhookEventPayloadResource updatedAt(OffsetDateTime updatedAt) {
    this.updatedAt = updatedAt;
    return this;
  }

  /**
   * The date and time when the resource was last updated.
   * @return updatedAt
   */
  @javax.annotation.Nullable
  public OffsetDateTime getUpdatedAt() {
    return updatedAt;
  }

  public void setUpdatedAt(OffsetDateTime updatedAt) {
    this.updatedAt = updatedAt;
  }


  public WebhookEventPayloadResource dashboardUrl(String dashboardUrl) {
    this.dashboardUrl = dashboardUrl;
    return this;
  }

  /**
   * The URL for viewing the resource on Onfido Dashboard.
   * @return dashboardUrl
   */
  @javax.annotation.Nullable
  public String getDashboardUrl() {
    return dashboardUrl;
  }

  public void setDashboardUrl(String dashboardUrl) {
    this.dashboardUrl = dashboardUrl;
  }


  public WebhookEventPayloadResource workflowId(UUID workflowId) {
    this.workflowId = workflowId;
    return this;
  }

  /**
   * The unique identifier for the Workflow.
   * @return workflowId
   */
  @javax.annotation.Nullable
  public UUID getWorkflowId() {
    return workflowId;
  }

  public void setWorkflowId(UUID workflowId) {
    this.workflowId = workflowId;
  }


  public WebhookEventPayloadResource workflowRunId(UUID workflowRunId) {
    this.workflowRunId = workflowRunId;
    return this;
  }

  /**
   * Get workflowRunId
   * @return workflowRunId
   */
  @javax.annotation.Nullable
  public UUID getWorkflowRunId() {
    return workflowRunId;
  }

  public void setWorkflowRunId(UUID workflowRunId) {
    this.workflowRunId = workflowRunId;
  }


  public WebhookEventPayloadResource workflowVersionId(Integer workflowVersionId) {
    this.workflowVersionId = workflowVersionId;
    return this;
  }

  /**
   * The identifier for the Workflow version.
   * @return workflowVersionId
   */
  @javax.annotation.Nullable
  public Integer getWorkflowVersionId() {
    return workflowVersionId;
  }

  public void setWorkflowVersionId(Integer workflowVersionId) {
    this.workflowVersionId = workflowVersionId;
  }


  public WebhookEventPayloadResource taskDefId(String taskDefId) {
    this.taskDefId = taskDefId;
    return this;
  }

  /**
   * The identifier for the Task Definition.
   * @return taskDefId
   */
  @javax.annotation.Nullable
  public String getTaskDefId() {
    return taskDefId;
  }

  public void setTaskDefId(String taskDefId) {
    this.taskDefId = taskDefId;
  }


  public WebhookEventPayloadResource taskDefVersion(String taskDefVersion) {
    this.taskDefVersion = taskDefVersion;
    return this;
  }

  /**
   * The task definition version.
   * @return taskDefVersion
   */
  @javax.annotation.Nullable
  public String getTaskDefVersion() {
    return taskDefVersion;
  }

  public void setTaskDefVersion(String taskDefVersion) {
    this.taskDefVersion = taskDefVersion;
  }


  public WebhookEventPayloadResource input(Object input) {
    this.input = input;
    return this;
  }

  /**
   * Input object with the fields used by the Task execution.
   * @return input
   */
  @javax.annotation.Nullable
  public Object getInput() {
    return input;
  }

  public void setInput(Object input) {
    this.input = input;
  }


  public WebhookEventPayloadResource output(Object output) {
    this.output = output;
    return this;
  }

  /**
   * Value field (it can be an Object, List, etc.) with the fields produced by the Task execution.
   * @return output
   */
  @javax.annotation.Nullable
  public Object getOutput() {
    return output;
  }

  public void setOutput(Object output) {
    this.output = output;
  }


  public WebhookEventPayloadResource reasons(List<String> reasons) {
    this.reasons = reasons;
    return this;
  }

  public WebhookEventPayloadResource addReasonsItem(String reasonsItem) {
    if (this.reasons == null) {
      this.reasons = new ArrayList<>();
    }
    this.reasons.add(reasonsItem);
    return this;
  }

  /**
   * The reasons the Workflow Run outcome was reached. Configurable when creating the Workflow Version.
   * @return reasons
   */
  @javax.annotation.Nullable
  public List<String> getReasons() {
    return reasons;
  }

  public void setReasons(List<String> reasons) {
    this.reasons = reasons;
  }


  public WebhookEventPayloadResource link(WorkflowRunLink link) {
    this.link = link;
    return this;
  }

  /**
   * Object for the configuration of the Workflow Run link.
   * @return link
   */
  @javax.annotation.Nullable
  public WorkflowRunLink getLink() {
    return link;
  }

  public void setLink(WorkflowRunLink link) {
    this.link = link;
  }


  public WebhookEventPayloadResource error(WorkflowRunError error) {
    this.error = error;
    return this;
  }

  /**
   * Error object that details why a Workflow Run is in Error status.
   * @return error
   */
  @javax.annotation.Nullable
  public WorkflowRunError getError() {
    return error;
  }

  public void setError(WorkflowRunError error) {
    this.error = error;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the WebhookEventPayloadResource instance itself
   */
  public WebhookEventPayloadResource putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WebhookEventPayloadResource webhookEventPayloadResource = (WebhookEventPayloadResource) o;
    return Objects.equals(this.id, webhookEventPayloadResource.id) &&
        Objects.equals(this.applicantId, webhookEventPayloadResource.applicantId) &&
        Objects.equals(this.createdAt, webhookEventPayloadResource.createdAt) &&
        Objects.equals(this.updatedAt, webhookEventPayloadResource.updatedAt) &&
        Objects.equals(this.dashboardUrl, webhookEventPayloadResource.dashboardUrl) &&
        Objects.equals(this.workflowId, webhookEventPayloadResource.workflowId) &&
        Objects.equals(this.workflowRunId, webhookEventPayloadResource.workflowRunId) &&
        Objects.equals(this.workflowVersionId, webhookEventPayloadResource.workflowVersionId) &&
        Objects.equals(this.taskDefId, webhookEventPayloadResource.taskDefId) &&
        Objects.equals(this.taskDefVersion, webhookEventPayloadResource.taskDefVersion) &&
        Objects.equals(this.input, webhookEventPayloadResource.input) &&
        Objects.equals(this.output, webhookEventPayloadResource.output) &&
        Objects.equals(this.reasons, webhookEventPayloadResource.reasons) &&
        Objects.equals(this.link, webhookEventPayloadResource.link) &&
        Objects.equals(this.error, webhookEventPayloadResource.error)&&
        Objects.equals(this.additionalProperties, webhookEventPayloadResource.additionalProperties);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, applicantId, createdAt, updatedAt, dashboardUrl, workflowId, workflowRunId, workflowVersionId, taskDefId, taskDefVersion, input, output, reasons, link, error, additionalProperties);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WebhookEventPayloadResource {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    applicantId: ").append(toIndentedString(applicantId)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("    dashboardUrl: ").append(toIndentedString(dashboardUrl)).append("\n");
    sb.append("    workflowId: ").append(toIndentedString(workflowId)).append("\n");
    sb.append("    workflowRunId: ").append(toIndentedString(workflowRunId)).append("\n");
    sb.append("    workflowVersionId: ").append(toIndentedString(workflowVersionId)).append("\n");
    sb.append("    taskDefId: ").append(toIndentedString(taskDefId)).append("\n");
    sb.append("    taskDefVersion: ").append(toIndentedString(taskDefVersion)).append("\n");
    sb.append("    input: ").append(toIndentedString(input)).append("\n");
    sb.append("    output: ").append(toIndentedString(output)).append("\n");
    sb.append("    reasons: ").append(toIndentedString(reasons)).append("\n");
    sb.append("    link: ").append(toIndentedString(link)).append("\n");
    sb.append("    error: ").append(toIndentedString(error)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("id");
    openapiFields.add("applicant_id");
    openapiFields.add("created_at");
    openapiFields.add("updated_at");
    openapiFields.add("dashboard_url");
    openapiFields.add("workflow_id");
    openapiFields.add("workflow_run_id");
    openapiFields.add("workflow_version_id");
    openapiFields.add("task_def_id");
    openapiFields.add("task_def_version");
    openapiFields.add("input");
    openapiFields.add("output");
    openapiFields.add("reasons");
    openapiFields.add("link");
    openapiFields.add("error");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to WebhookEventPayloadResource
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!WebhookEventPayloadResource.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in WebhookEventPayloadResource is not found in the empty JSON string", WebhookEventPayloadResource.openapiRequiredFields.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("id") != null && !jsonObj.get("id").isJsonNull()) && !jsonObj.get("id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("id").toString()));
      }
      if ((jsonObj.get("applicant_id") != null && !jsonObj.get("applicant_id").isJsonNull()) && !jsonObj.get("applicant_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `applicant_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("applicant_id").toString()));
      }
      if ((jsonObj.get("dashboard_url") != null && !jsonObj.get("dashboard_url").isJsonNull()) && !jsonObj.get("dashboard_url").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `dashboard_url` to be a primitive type in the JSON string but got `%s`", jsonObj.get("dashboard_url").toString()));
      }
      if ((jsonObj.get("workflow_id") != null && !jsonObj.get("workflow_id").isJsonNull()) && !jsonObj.get("workflow_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `workflow_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("workflow_id").toString()));
      }
      if ((jsonObj.get("workflow_run_id") != null && !jsonObj.get("workflow_run_id").isJsonNull()) && !jsonObj.get("workflow_run_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `workflow_run_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("workflow_run_id").toString()));
      }
      if ((jsonObj.get("task_def_id") != null && !jsonObj.get("task_def_id").isJsonNull()) && !jsonObj.get("task_def_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `task_def_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("task_def_id").toString()));
      }
      if ((jsonObj.get("task_def_version") != null && !jsonObj.get("task_def_version").isJsonNull()) && !jsonObj.get("task_def_version").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `task_def_version` to be a primitive type in the JSON string but got `%s`", jsonObj.get("task_def_version").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("reasons") != null && !jsonObj.get("reasons").isJsonNull() && !jsonObj.get("reasons").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `reasons` to be an array in the JSON string but got `%s`", jsonObj.get("reasons").toString()));
      }
      // validate the optional field `link`
      if (jsonObj.get("link") != null && !jsonObj.get("link").isJsonNull()) {
        WorkflowRunLink.validateJsonElement(jsonObj.get("link"));
      }
      // validate the optional field `error`
      if (jsonObj.get("error") != null && !jsonObj.get("error").isJsonNull()) {
        WorkflowRunError.validateJsonElement(jsonObj.get("error"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!WebhookEventPayloadResource.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'WebhookEventPayloadResource' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<WebhookEventPayloadResource> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(WebhookEventPayloadResource.class));

       return (TypeAdapter<T>) new TypeAdapter<WebhookEventPayloadResource>() {
           @Override
           public void write(JsonWriter out, WebhookEventPayloadResource value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additional properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   JsonElement jsonElement = gson.toJsonTree(entry.getValue());
                   if (jsonElement.isJsonArray()) {
                     obj.add(entry.getKey(), jsonElement.getAsJsonArray());
                   } else if (jsonElement.isJsonObject()) { 
                     obj.add(entry.getKey(), jsonElement.getAsJsonObject());
                   }
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public WebhookEventPayloadResource read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             JsonObject jsonObj = jsonElement.getAsJsonObject();
             // store additional fields in the deserialized instance
             WebhookEventPayloadResource instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of WebhookEventPayloadResource given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of WebhookEventPayloadResource
   * @throws IOException if the JSON string is invalid with respect to WebhookEventPayloadResource
   */
  public static WebhookEventPayloadResource fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, WebhookEventPayloadResource.class);
  }

  /**
   * Convert an instance of WebhookEventPayloadResource to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

