/*
 * Onfido Public API v3.6
 * The Onfido Public API (v3.6)
 *
 * The version of the OpenAPI document: v3.6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.onfido.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.JsonElement;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets workflow_run_status
 */
@JsonAdapter(WorkflowRunStatus.Adapter.class)
public enum WorkflowRunStatus {
  
  PROCESSING("processing"),
  
  AWAITING_INPUT("awaiting_input"),
  
  AWAITING_CLIENT_INPUT("awaiting_client_input"),
  
  APPROVED("approved"),
  
  DECLINED("declined"),
  
  REVIEW("review"),
  
  ABANDONED("abandoned"),
  
  ERROR("error"),
  
  UNKNOWN_DEFAULT_OPEN_API("unknown_default_open_api");

  private String value;

  WorkflowRunStatus(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static WorkflowRunStatus fromValue(String value) {
    for (WorkflowRunStatus b : WorkflowRunStatus.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    return UNKNOWN_DEFAULT_OPEN_API;
  }

  public static class Adapter extends TypeAdapter<WorkflowRunStatus> {
    @Override
    public void write(final JsonWriter jsonWriter, final WorkflowRunStatus enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public WorkflowRunStatus read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return WorkflowRunStatus.fromValue(value);
    }
  }

  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
    String value = jsonElement.getAsString();
    WorkflowRunStatus.fromValue(value);
  }
}

